---
name: Role Tests
on:
  push:
    branches:
      - master

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install community.docker

      - name: Run molecule tests
        run: molecule -v test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
